### ISSUE TITLE
after start immediate restart of Homebridge (solved)

### ISSUE THREAD

**Issue by Tymo3** [vectronic/homebridge-shinobi#1]
First of all - thanks for great work!

I have Homebridge on raspberry pi.
I had an issue with immediate restart of Homebridge (instant restart) after installing and configuring this plugin.
And there was no error, nothing in Homebridge logs.

Then I set DEBUG for Homebridge (created file /etc/default/homebridge, with only line DEBUG=*).
After restart homebridge shown that port 8443 is already taken...

So changing to port 9443 solved problem.
web_hook_port": "9443"

I hope it can help anybody using this plugin.
t

**Comment by vectronic** [comment]
Thanks for your appreciation!
