### ISSUE TITLE
Https Key Path and Https Cert Path keep coming back

### ISSUE THREAD

**Issue by rschitz** [vectronic/homebridge-shinobi#23]
Every time i need to update the setting using the GUI, the https cert path are refilled even if its not in the config file.
I have to remove then every time otherwise the plugin fail to start.
![image](https://user-images.githubusercontent.com/8385646/235539141-db4261f4-6352-4255-8cda-4b03e7321c85.png)
![image](https://user-images.githubusercontent.com/8385646/235539451-9b60168b-6a81-4367-9460-d69eaa7b2cdd.png)

**Comment by vectronic** [comment]
It is because it has a default specified.

**Comment by rschitz** [comment]
maybe let the default blank and move the path example to the comment?

**Comment by vectronic** [comment]
This should be fixed in 3.1.4 - let me know how it works for you....
